authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: true
  group_base: ou=people,dc=test,dc=com
  group_membership_attribute: member
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
  require_attribute:
    objectClass: inetOrgPerson
## Environment

development:
  host: localhost
  port: 636
  attribute: cn
  base: ou=people,dc=test,dc=com
  ssl: start_tls
  <<: *AUTHORIZATIONS
